version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user12345
      - POSTGRES_DB=assessment
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-backend:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: go_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=user12345
      - DB_NAME=assessment
      - DB_PORT=5432
    depends_on:
      - db

  laravel-frontend:
    build:
      context: ./frontend-laravel
      dockerfile: Dockerfile
    container_name: laravel_frontend
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - go-backend
      - db
    environment:
      - GO_API_URL=http://127.0.0.1:8080/api

volumes:
  postgres_data: